### ISSUE TITLE
Integrate navx mxp into code

### ISSUE THREAD

**Issue by theEnchantress** [DeepBlueRobotics/RobotCode2017#12]
1. Refer to the following website in order to download the library to control the sensor:
http://www.pdocs.kauailabs.com/navx-mxp/software/roborio-libraries/java/
Refer to this link for some examples of how to code for it:
http://www.pdocs.kauailabs.com/navx-mxp/examples/

2. Replace the gyro in our Robot2017 code with the navX MXP. Ensure that AutoDrive will work the way it's supposed to.

Do the latter if you feel like it:

Get your code checked thouroughly, and not necessarily by Ana. Explain how the navX is different from a regular gyro to them.

Brainstorm other cool things we could have the robot do with this sensor (based on the examples and the source code) and comment them in Github under this issue!

**Comment by theEnchantress** [comment]
http://www.kauailabs.com/public_files/navx-mxp/apidocs/java/com/kauailabs/navx/frc/AHRS.html

**Comment by kevinzwang** [comment]
yay done but have to test too
