### ISSUE TITLE
Implement infrared sensor on climber for sensing whether we have actuated the top plate

### ISSUE THREAD

**Issue by theEnchantress** [DeepBlueRobotics/RobotCode2017#21]
- [x] Do testing on a practice board with the IR sensor to see what values it needs to register red or blue light
- [x] Change the `Climber` class to utilize the IR sensor to return whether we have actuated the plate or not
- [x] Change the `Climb` command to stop the winch once we see that the plate has been activated. Figure out what we need to do in case the climber starts slipping.
- [x] Also add in functionality to slow down the climber motor if our current draw for the climber is above a certain level.

**Comment by davidfang199** [comment]
Not done, have to find color range still with AI

**Comment by theEnchantress** [comment]
Have to find different sensor - VEX line trackers do not suit our purpose.

**Comment by theEnchantress** [comment]
Different sensor found: http://www.vexrobotics.com/276-2158.html

Updated requirements for issue.
