### ISSUE TITLE
Make sure shooter motor does not stall

### ISSUE THREAD

**Issue by theEnchantress** [DeepBlueRobotics/RobotCode2017#24]
In the shooter class, write a method that cuts power to the shooter motor if we are sending a signal above a certain threshold, but the encoder is saying that the wheel isn't moving. 

Ensure that this method only runs if the shooter encoder itself has been deemed functional. Have a getPref() that can tell whether we have tested the encoder and it works in other scenarios.

**Comment by kevinzwang** [comment]
"Done, just need to test" -David
