### ISSUE TITLE
LED light strip programming 

### ISSUE THREAD

**Issue by theEnchantress** [DeepBlueRobotics/RobotCode2017#25]
Work with Jacob Gottesman to figure out how best to program and power the light strips, and where to place them on the robot. You may want to program them either using a PWM output port on the roboRIO for each light color, or using an Arduino.

**Comment by theEnchantress** [comment]
Using the raspberry pi might be the best idea. See: https://thepihut.com/blogs/raspberry-pi-tutorials/27968772-turning-on-an-led-with-your-raspberry-pis-gpio-pins
^this should work the same with an led strip as it does with an LED, the wiring would just be different. If it doesn't work quite how it's supposed to, do more internet research

Consult with Kevin about running code on the RPi, and test the LED strip out. In the end, even getting it to display just one solid color would be enough, it might be cooler to have underglow on the robot than to make it flashy.

**Comment by denledsunky** [comment]
Thank you share, i find it but no see place

**Comment by vimanto** [comment]
please am new out here. i have some led strips but i cant write the programm i have also used Led edit but cant work with SD card. help needed
