### ISSUE TITLE
Configure our two Raspberry Pis

### ISSUE THREAD

**Issue by theEnchantress** [DeepBlueRobotics/RobotCode2017#32]
For each processor:

- [ ] [Download NOOBS and install on the SD chip](https://www.raspberrypi.org/learning/software-guide/quickstart/)
- [ ] Boot up the Pi with the SD chip inserted, and follow all installation instructions
- [ ] Connect the Pi to the internet via ethernet, and using `sudo pip install` processes download numpy, opencv-python, and pynetworktables. Install git with `sudo apt-get install git-all`. Also run `sudo apt-get install uvcdynctrl` to install the webcam utilities we need.
- [ ] Copy our Robot2017 Repo onto some directory in the Documents folder of the RPi
- [ ] After finishing, work with with Ana/Kevin to test the RPi and make sure it all works like it needs to

**Comment by davidfang199** [comment]
Would the rpi still work after it gets unplugged in the middle of smthing?
