### ISSUE TITLE
Investigate how to use the Talon SRX for controlling the speed of a motor, and implement for the shooter

### ISSUE THREAD

**Issue by theEnchantress** [DeepBlueRobotics/RobotCode2017#34]
The shooter prototyping team has decided to use a Talon SRX Motor Controller, because the motor controller itself has the capability to use PID to keep the shooter's speed at some target, more effectively than we would be able to do with the roboRIO. We would be communicating over the roboRIO's CAN interface, plugging in an encoder directly to the motor, and giving it target speed input in the format it wants.

- [ ] Investigate how to implement it in our code.
- [ ] Implement it in our code.
- [ ] Make sure that you leave in all of our regular methods for regulating PID, but make the commands themselves run based off of the Talon SRX's PID. We will leave in the regular PID methods as backup in case this does not work for some reason.
- [ ] Test everything you need to on a practice board, off the robot, to be as sure as possible that your code will work once we get to the actual robot.

Check out the following resources:
http://www.ctr-electronics.com/downloads/pdf/Talon%20SRX%20Software%20Reference%20Manual.pdf*
http://www.ctr-electronics.com/downloads/api/java/html/index.html
https://github.com/CrossTheRoadElec/FRC-Examples/tree/master/JAVA_VelocityClosedLoop

**Comment by theEgotisticalGiraffe** [comment]
Someone else can work on this because I've been too busy with modelling stuff.

**Comment by lhmcgann** [comment]
link to download:
http://www.ctr-electronics.com/hro.html#product_tabs_technical_resources
It's the CTRE Toolsuite Installer 4.something
