### ISSUE TITLE
Create 2-day code testing plan

### ISSUE THREAD

**Issue by theEnchantress** [DeepBlueRobotics/RobotCode2017#35]

**Comment by ofeuchtw** [comment]
### Test buttons: 
Quickly test whether each button is doing the correct function for the correct amount of time, etc.
1. manipulator

- [ ] feedOutButton
- [ ] feedInButton
- [ ] winchButton
- [ ] shootOutButton
- [ ] outputButton
- [ ] intakeButton
- [ ] toggleIntakeButton
- [ ] autoUSAdjustButton
2. right joystick
- [ ] autoShootRoutineButton
- [ ] gradualDriveButton
- [ ] shiftGearsButton
- [ ] toggleFlipper
3. left joystick
- [ ] switchDriveButton
- [ ] autoAlignGearRoutineButton

### Test sensors:
Refine accuracy of driving
- [ ] Tune Encoders
- [ ] Test Drive PID
- [ ] Test Turn PID

### Test commands:
Check whether these commands work, PID is separate
- [ ] AutoDrive
- [ ] ToggleIntakeRamp
- [ ] AutoDelay
- [ ] AutoAlignGear (future: verify it works with shoot parameter = true)
- [ ] DeployGear
- [ ] FollowTrajectory
- [ ] RunFeeder

### Test Modes:
Need to prepare field replica to verify that the robot doesn't overshoot targets, etc.
- [ ] AutoModeBoilerSide
- [ ] AutoModeCenter
- [ ] AutoModeLoadSide
- [ ] Climb
