### ISSUE TITLE
Learn vision programming - with python and OpenCV

### ISSUE THREAD

**Issue by theEnchantress** [DeepBlueRobotics/RobotCode2017#5]
The idea behind vision programming is the need to identify certain objects using a camera. We will be learning how to do this using a library called Open-CV, and in python in order to run our programs on an offboard processor.

This project requires using the specs of the vision targets on the boiler to accurately aim toward and shoot for the boiler. If you figure out how to tell your current distance from the boiler based on the size of the targets on the screen, do so.

The important part to extract from the vision component are the horizontal and vertical distances of the centers of the targets from the center of an image. Once you're able to do that, you have done a majority of the work.

**Comment by theEnchantress** [comment]
If beginning to work: 

1. Install the opencv-py library on your computer by running
`pip install opencv-python` from you command line. 
If this doesn't work on the first try call Ana over for assistance or! Troubleshoot on your own! : D

2. Visit this website:
http://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_table_of_contents_gui/py_table_of_contents_gui.html

And run through as many tutorials as you feel the need to, up to "Video Analysis" tutorials.

3. Take a look at other teams' vision tracking, for example https://github.com/Team3574/2013VisionCode. Search "FRC python vision" or something like that

**Comment by Gabe-Mitnick** [comment]
:feelsgood::squirrel:

**Comment by kevinzwang** [comment]
:hurtrealbad:

**Comment by Gabe-Mitnick** [comment]
we done did that thang
